config/routes.rb
Graphite::Engine.routes.draw do

  resources :elective_blocks do
    resources :blocks, controller: "elective_block/blocks"
    collection do
      post :create_and_edit
      get :event_pipe
      delete :collection_destroy
    end
    member do
      patch :enroll
      patch :perform_scheduling
    end

    resources :modules
  end
  namespace :reports do
    resources :elective_blocks, :only => [] do
      collection do
        get :student_list
        get :all_student_list
      end
    end
  end

end

app/models/graphite/elective_block.rb
class Graphite::ElectiveBlock < ActiveRecord::Base

  include ::Workflow

  workflow_column :state
  # Workflow is used only for elective blocks having blocks.
  workflow do
    state :default do
      event :schedule, :transitions_to => :scheduled
    end
    state :scheduled do
      event :complete, :transitions_to => :default
    end
  end

  translates :name
  globalize_accessors :locales => I18n.available_locales

  belongs_to :block_type
  has_many :modules, class_name: "Graphite::ElectiveBlock::ElectiveModule",
    dependent: :destroy
  accepts_nested_attributes_for :modules, :reject_if => lambda { |mod|
    mod[:name].blank? || mod[:owner_id].blank?
  }
  has_many :semester_assignments, :class_name => "Graphite::ElectiveBlock::SemesterAssignment",
    dependent: :destroy
  has_many :semester_numbers, through: :semester_assignments
  has_many :elective_block_studies, :class_name => "Graphite::ElectiveBlockStudies",
    dependent: :destroy
  has_many :studies, through: :elective_block_studies
  has_many :annual_studies, -> { distinct },
    through: :elective_block_studies, source: :studies
  has_many :elective_blocks, class_name: 'Graphite::ElectiveBlock::Block',
    dependent: :destroy
  accepts_nested_attributes_for :elective_blocks, :reject_if => lambda { |elective_block|
    elective_block[:module_ids].blank? || elective_block[:name].blank?
  }, allow_destroy: true
  has_many :enrollments, class_name: 'Graphite::ElectiveBlock::Enrollment'
  accepts_nested_attributes_for :enrollments, :reject_if => lambda { |enrollment|
    reject = true
    if enrollment[:state] == 'queued'
      reject &&= enrollment[:priority].blank?
    else
      reject &&= enrollment[:enroll] == "0"
    end
    reject
  }, allow_destroy: true
  belongs_to :annual
  belongs_to :semester

  scope :persisted, -> { where(state: :persisted) }
  scope :for_semester, ->(semester) do
    select("DISTINCT #{Graphite::ElectiveBlock.table_name}.*")
    .joins(:modules)
    .where("#{Graphite::ElectiveBlock::ElectiveModule.table_name}.semester_number" => semester)
  end
  scope :for_student_semester, ->(semester) do
    select("DISTINCT #{Graphite::ElectiveBlock.table_name}.*")
    .joins(:modules)
    .group("#{Graphite::ElectiveBlock.table_name}.id")
    .having("MIN(#{Graphite::ElectiveBlock::ElectiveModule.table_name}.semester_number) IN (?)", semester)
  end
  scope :by_semester, ->(semester) { for_semester(semester) }
  scope :by_semester_season, ->(semester) { where(:semester_id => semester) }
  scope :by_studies, ->(studies) do
    joins(:studies)
    .where("#{Studies.table_name}.id" => studies)
  end
  scope :by_annual, ->(annual) { where(:annual_id => annual) }
  scope :by_block_type, ->(block_type) { where(:block_type_id => block_type) }
  scope :parents_only, -> { where("#{Graphite::ElectiveBlock.table_name}.elective_block_id IS NULL") }
  scope :for_student, ->(student) do
    joins(:elective_block_studies)
    .where("#{Graphite::ElectiveBlockStudies.table_name}.studies_id IN (?)",
           student.student_studies.collect(&:studies_id))
  end


  def <=>(other)
    name <=> other.name
  end

  def enrollments_pending?(student)
    @enrollments_pending = {} unless defined?(@enrollments_pending)
    return @enrollments_pending[student] if @enrollments_pending.has_key?(student)
    @enrollments_pending[student] = enrollments.select("1 AS ONE").pending
    .for_student(student)
    .present?
  end

  def student_any_accepted_enrollment?(student)
    enrollments.select("1 AS ONE")
    .for_student(student)
    .accepted
    .present?
  end

  def student_queued?(student)
    enrollments.select("1 AS ONE")
    .for_student(student)
    .queued
    .present?
  end

  def student_enrolled?(student)
    @student_enrolled = {} unless defined?(@student_enrolled)
    return @student_enrolled[student] if @student_enrolled.has_key?(student)
    @student_enrolled[student] = enrollments
    .for_student(student)
    .any?
  end

  def student_accepted?(student)
    student_accepted =
      enrollments.for_student(student).accepted.count == min_modules_amount
    unless enroll_by_average_grade?
      student_accepted &&= !enrollments_pending?(student)
    end
    student_accepted
  end

  def enroll_by_average_grade?
    enroll_by_avg_grade
  end

  def scheduling_needed?
    enroll_by_average_grade? && enrollments.not_versioned.queued.any? &&
      current_state == 'default'
  end

  def self.include_peripherals
    includes(:annual, :translations, :block_type => :translations,
             :modules => [:translations, :employee => :employee_title])
  end

end

app/models/graphite/elective_block/block.rb
class Graphite::ElectiveBlock::Block < ActiveRecord::Base

  translates :name
  globalize_accessors :locales => I18n.available_locales

  belongs_to :elective_block
  has_many :block_modules, class_name: "Graphite::ElectiveBlock::BlockModule",
    dependent: :destroy, foreign_key: :elective_block_id
  has_many :modules, through: :block_modules,
    class_name: "Graphite::ElectiveBlock::ElectiveModule", source: :elective_module
  has_many :enrollments, class_name: "Graphite::ElectiveBlock::Enrollment",
    dependent: :destroy
  has_many :accepted_students,
    -> { where("#{Graphite::ElectiveBlock::Enrollment.table_name}.state" => 'accepted') },
    through: :enrollments, source: :student

  def enrollment_for_student(student)
    enrollments.where(student_id: student).not_versioned.first
  end

end

app/models/graphite/elective_block/block_module.rb
class Graphite::ElectiveBlock::BlockModule < ActiveRecord::Base

  belongs_to :block, class_name: 'Graphite::ElectiveBlock::Block',
    foreign_key: :elective_block_id
  belongs_to :elective_module

end

app/models/graphite/elective_block/semester_number.rb
class Graphite::ElectiveBlock::SemesterNumber < ActiveRecord::Base

end

app/controllers/graphite/application_controller.rb
module Graphite
  class ApplicationController < ActionController::Base
  end
end

app/controllers/graphite/elective_block/blocks_controller.rb
class Graphite::ElectiveBlock::BlocksController < GraphiteController

  authorize_resource :class => "Graphite::ElectiveBlock"

  def new
    preload
    @block = Graphite::ElectiveBlock::Block.new(elective_block: @elective_block)
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def create
    new_block = Graphite::ElectiveBlock::Block.new(block_params)
    new_block.save
    preload
    @block = Graphite::ElectiveBlock::Block.new(elective_block: @elective_block)
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def edit
    @block = Graphite::ElectiveBlock::Block.find(params[:id])
    preload
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def update
    @block = Graphite::ElectiveBlock::Block.find(params[:id])
    @block.update(block_params)
    preload

    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def destroy
    old_block = Graphite::ElectiveBlock::Block.find(params[:id])
    @block = old_block.elective_block.elective_blocks.build
    old_block.destroy
    preload
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  private

  def block_params
    attrs = params.require(:elective_block).permit(:elective_blocks_attributes =>
        [:id, :name, :elective_block_id, :min_ects_amount, :student_amount,
        :module_ids => []])
    attrs.values.first.values.first
  end

  def preload
    @elective_block = Graphite::ElectiveBlock
    .includes(:translations, :modules => [:translations, :employee => :employee_title])
    .find(params[:elective_block_id])
    @blocks = @elective_block.elective_blocks.includes(:translations).sort
    @modules = @elective_block.modules.sort
  end
end

app/controllers/graphite/modules_controller.rb
class Graphite::ModulesController < GraphiteController

  authorize_resource :class => "Graphite::ElectiveBlock::ElectiveModule"

  def new
    preload
    @module = Graphite::ElectiveBlock::ElectiveModule.new(elective_block: @elective_block)
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def create
    @module = Graphite::ElectiveBlock::ElectiveModule.create(module_params)
    preload
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def edit
    @module = Graphite::ElectiveBlock::ElectiveModule.find(params[:id])
    preload
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def update
    @module = Graphite::ElectiveBlock::ElectiveModule.find(params[:id])
    @module.update(module_params)
    preload
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  def destroy
    old_mod = Graphite::ElectiveBlock::ElectiveModule.find(params[:id])
    @module = old_mod.elective_block.modules.build
    old_mod.destroy
    preload
    respond_to do |f|
      f.js do
        render layout: false
      end
    end
  end

  private

  def module_params
    attrs = params.require(:elective_block).permit(:modules_attributes => [:id, :name,
        :www, :owner_id, :student_amount, :ects_amount, :semester_number, :elective_block_id])
    attrs.values.first.values.first
  end

  def preload
    @elective_block = Graphite::ElectiveBlock
    .includes(:modules => [:translations, :employee => :employee_title])
    .find(params[:elective_block_id])
    @modules = @elective_block.modules.sort
    if (block_id = params[:elective_block][:elective_blocks_attributes].values.first['id']).present?
      @block = Graphite::ElectiveBlock::Block.find(block_id)
    end
  end
end

app/controllers/graphite/reports/elective_blocks_controller.rb
class Graphite::Reports::ElectiveBlocksController < GraphiteController


  def student_list
    authorize! :manage, :elective_blocks_reports

    respond_to do |format|
      format.xlsx do
        students = Student.enrolled_to_elective_blocks
        cache_key = fragment_cache_key_for(students)
        data = Rails.cache.fetch(cache_key) do
          file = Graphite::Xlsx::AcceptedStudentList.new(students)
          data = file.to_xlsx
          Rails.cache.write(cache_key, data)
          data
        end
        send_data(data, :filename => "#{t(:label_elective_block_report_student_list)}.xlsx",
                  :type => "application/xlsx", :disposition => "inline")
      end
    end
  end

  def all_student_list
    authorize! :manage, :elective_blocks_reports

    respond_to do |format|
      format.xlsx do
        students = Student.students_with_enrollments
        cache_key = fragment_cache_key_for(students)
        data = Rails.cache.fetch(cache_key) do
          file = Graphite::Xlsx::AllStudentList.new(students)
          data = file.to_xlsx
          Rails.cache.write(cache_key, data)
          data
        end
        send_data(data, :filename => "#{t(:label_elective_block_export_all_student_list)}.xlsx",
                  :type => "application/xlsx", :disposition => "inline")
      end
    end
  end
end

app/controllers/graphite_controller.rb
class GraphiteController < ApplicationController

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

  def url_options(options={})
    logger.debug "url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

end

app/helpers/graphite/application_helper.rb
module Graphite
  module ApplicationHelper
  end
end

app/helpers/graphite/elective_blocks_common_helper.rb
module Graphite::ElectiveBlocksCommonHelper

  def elective_block_block_of_subjects_selection(elective_block)
    I18n.t "label_elective_block_type_#{elective_block.block_type.try(:const_name)}",
      counted_blocks: I18n.t('misc.block_count', count: elective_block.min_modules_amount.to_i),
      m: elective_block.elective_blocks.count
  end

  def elective_block_n_from_m_subjects_selection(elective_block)
    I18n.t "label_elective_block_type_#{elective_block.block_type.try(:const_name)}",
      counted_subjects: I18n.t('misc.subject_count', count: elective_block.min_modules_amount.to_i),
      m: elective_block.modules.count
  end

end

app/helpers/graphite/elective_blocks_helper.rb
module Graphite::ElectiveBlocksHelper

  include Graphite::ElectiveBlocksCommonHelper

  def block_type_filter_content
    return @block_type_filter if defined?(@block_type_filter)
    @block_type_filter = [[t(:label_all), nil]] | Graphite::ElectiveBlock::BlockType.all
    .collect {|bt| ["#{bt.name} (#{t("label_elective_block_type_#{bt.const_name}_letter")})", bt.id]}
  end

  def studies_filter_content
    return @studies_filter if defined?(@studies_filter)
    @studies_filter = [[t(:label_all), nil]] | Studies
    .include_peripherals
    .load
    .sort_by {|s| [s.course.name, s.study_type_id, s.study_degree_id] }
    .collect {|s| [[s.course.name, *("(#{s.specialization.name})" if s.specialty_id.present?),
                    " - #{s.study_type.name.downcase} #{s.study_degree.name.camelize(:lower)}"].join(" "),
                   s.id]}
  end

  def semester_season_filter_content
    return @semester_season_filter if defined?(@semester_filtersemester_season_filter)
    @semester_season_filter = [[t(:label_all), nil]] | Semester
    .includes(:translations).all.collect { |sem| [sem.name, sem.id] }
  end

  def semester_studies_filter_content
    return @semester_filter if defined?(@semester_filter)
    @semester_filter = [[t(:label_all), nil]] | (1..8).collect {|i| [i, i]}
  end

  def elective_can_enroll?
    return @elective_can_enroll if defined?(@elective_can_enroll)
    @elective_can_enroll = elective_enrollments_available?
    @elective_can_enroll &&= !@elective_block.enrollments_pending?(current_user.student)
  end

  def can_enroll_for_subject?(subject)
    @can_enroll_for_subject = {} unless defined?(@can_enroll_for_subject)
    return @can_enroll_for_subject[subject] if @can_enroll_for_subject.has_key?(subject)
    @can_enroll_for_subject[subject] = elective_can_enroll?
    unless current_user.student.elective_enrollments.for_subject(subject).any?
      @can_enroll_for_subject[subject] &&= subject.open_for_enrollments?
    end
    @can_enroll_for_subject[subject]
  end

  def elective_enrollments_available?
    return @enrollments_available if defined?(@enrollments_available)
    now = Time.now
    @enrollments_available = current_semester.elective_enrollments_begin <= now && now <= current_semester.elective_enrollments_end
  end

  def elective_block_enrollments_info
    if @elective_block.student_accepted?(current_user.verifable)
      content = alert(:success) do
        t(elective_enrollments_available? ? :label_elective_block_enrollment_accepted_desc_open : :label_elective_block_enrollment_accepted_desc_close)
      end
      return content
    elsif @elective_block.student_enrolled?(current_user.verifable)
      if @elective_block.enroll_by_average_grade?
        if current_user.verifable.has_queued_enrollments_for_module?(@elective_block)
          content = alert(:success) do
            t(elective_enrollments_available? ? :label_elective_block_enrollment_queued_desc_open : :label_elective_block_enrollment_accepted_desc_close)
          end
        end
      else
        content = alert(:info) do
          t(:label_elective_block_enrollment_pending_desc)
        end
      end
      return content
    end
    if !elective_enrollments_available?
      desc = t :label_elective_block_enrollment_unavailable, :from_day => l(current_semester.elective_enrollments_begin), :to_day => l(current_semester.elective_enrollments_end)
    elsif @elective_block.enrollments_pending?(current_user.student)
      desc = t :label_elective_block_enrollment_pending_desc
    elsif @elective_block.block_type.choose_n_from_m?
      if !@elective_block.student_accepted?(current_user.student)
        desc = t :label_elective_block_enrollment_n_from_m_incomplete, :subjects => t('misc.subject_count', :count => @elective_block.min_modules_amount)
      end
    elsif @elective_block.block_type.block_of_subjects?
      if @elective_block.enroll_by_average_grade?
        desc = t :label_elective_block_block_of_subjects_avg_grade_incomplete, :blocks => t('misc.block_count', :count => @elective_block.min_modules_amount)
      else
        desc = t :label_elective_block_block_of_subjects_incomplete, :blocks => t('misc.block_count', :count => @elective_block.min_modules_amount)
      end
    else
    end
    if defined?(desc) && desc.present?
      alert(:info) do
        raw desc
      end
    end
  end

  def student_enrollment_status(enrollment)
    if (status = @student_block_enrollments.detect {|e| e.block_id == enrollment.block_id}.try(:state)).present?
      klazz = case status
      when 'rejected' then 'text-danger'
      when 'accepted' then 'text-success'
      else ''
      end
      content_tag(:span, :class => klazz) do
        t("label_enrollment_state_#{status}")
      end
    end
  end

  private

  def alert(type)
    content_tag :div, :class => "alert alert-#{type}" do
      content_tag :p do
        yield
      end
    end
  end
end

app/views/graphite/elective_blocks/_blocks.html.erb
<div class="subsection-header">
  <h6>
    <%=t :label_elective_block_block_added %>
  </h6>
  <hr>
</div>
<table class="table">
  <tbody>
    <% if @blocks.any? {|block| !block.new_record? } %>
      <% @blocks.each do |block| %>
        <% next if block.new_record? %>
        <tr>
          <td>
            <%= block.name %>
          </td>
          <td>
            <%= link_to t(:label_edit), edit_elective_block_block_path(@elective_block, block), :class => "edit-element" %>
            <span class="sep">|</span>
            <%= link_to t(:label_destroy), elective_block_block_path(@elective_block, block), method: :delete, :class => "destroy-element" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center">
          <span>
            <%=t :label_elective_block_block_none_added %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= f.fields_for :elective_blocks, block do |g| %>
  <div class="subsection-header extra-margin">
    <h6>
      <%=t :label_elective_block_block_new %>
    </h6>
    <hr>
  </div>
  <div class="form-group extra-margin">
    <div class="row">
      <div class="col-md-16">
        <%= g.label :name, t(:label_elective_block_block_name) %>
        <%= g.text_field :name, :class => "form-control lazy-validate", :placeholder => t(:label_elective_block_block_name), :rows => 3  %>
      </div>
    </div>
  </div>
  <div class="form-group extra-margin">
    <%= g.label :module_ids, t(:label_subject_plural) %>
    <%= g.select :module_ids, options_for_select(@modules.collect {|mod| [mod.name, mod.id] }, g.object.module_ids), {}, :class => "form-control module-ids lazy-validate", :multiple => "multiple", :size => 6 %>
    <%= g.hidden_field :elective_block_id, :value => @elective_block.id %>
  </div>
  <div class="form-group extra-margin">
    <div class="row">
      <div class="col-md-8">
        <%= g.label :student_amount, t(:label_elective_block_student_amount) %>
        <%= g.select :student_amount, options_for_select([["--", ""]] | (5..200).step(5).to_a.collect {|i| [i,i] }, g.object.try(:student_amount)), {}, :class => "form-control student-amount" %>
      </div>
    </div>
  </div>
  <hr>
  <div class="pull-right">
    <%= g.button t(:label_cancel), :class => "btn btn-primary cancel-form", :'data-type' => 'block' %>
    <%= g.submit t(g.object.new_record? ? :label_add : :label_save), :class => "btn btn-danger save-block" %>
  </div>
  <div class="clearfix"></div>
  <div class="section-footer extra-margin">
    <hr>
  </div>
<% end %>

app/views/graphite/elective_blocks/_elective_block_header.html.erb
<div class="pull-right">
  <div class="row">
    <div class="col-md-7">
      <%= button_to t(:label_save_and_close), (@elective_block.new_record? ? elective_blocks_path : elective_block_path(@elective_block)), form: {class: "form-inline" }, :class => "btn btn-primary save-and-close" %>
      </div>
    </div>
  </div>

app/views/graphite/elective_blocks/_employee_block.html.erb
<tr class="fat-row">
  <td>
    <%= employee_block.name %>
  </td>
  <td>
    <%=t 'misc.subject_count', :count => employee_block.modules.length %>
  </td>
  <td>
    <%= "#{t :label_semester}: #{employee_block.modules.collect(&:semester_number).uniq.sort.join(", ")}" %>
  </td>
  <% if employee_block.student_amount.present? %>
    <td>
      <% if @elective_block.enroll_by_average_grade? %>
        <p>
          <%=t('misc.reservation_count', :count => employee_block.enrollments.not_versioned.queued_or_accepted.count) %>
          <br>
          <%=t( "misc.place_count", :count => employee_block.student_amount) %>
        </p>
      <% else %>
        <%= "#{employee_block.student_amount.to_i - employee_block.enrolled_students}/#{t( "misc.place_count", :count => employee_block.student_amount)}" %>
      <% end %>
    </td>
  <% end %>
  <td>
    <%= employee_block.modules.collect(&:ects_amount).reduce(&:+) %> ECTS
  </td>
</tr>
<% employee_block.modules.sort_by {|mod| mod.semester_number}.each do |mod| %>
  <tr>
    <td style="border: none;"></td>
    <td><%= mod.name %></td>
    <td>
      <%= "#{t :label_semester}: #{mod.semester_number}" %>
    </td>
    <% if employee_block.student_amount.present? %>
      <td></td>
    <% end %>
    <td>
      <%= mod.ects_amount %> ECTS
    </td>
  </tr>
<% end %>

app/views/graphite/elective_blocks/_subjects.html.erb
<div class="subsection-header">
  <h6>
    <%=t :label_elective_block_plural_added %>
  </h6>
  <hr>
</div>
<table class="table">
  <tbody>
    <% if @modules.any? {|mod| !mod.new_record? } %>
      <% @modules.each do |mod| %>
        <% next if mod.new_record? %>
        <tr>
          <td>
            <%= mod.name %>
          </td>
          <td>
            <%= mod.employee.try(:full_name) %>
          </td>
          <td>
            <%= "#{mod.semester_number} #{t( :label_semester)}" %>
          </td>
          <td>
            <%= mod.ects_amount %> ECTS
          </td>
          <td>
            <% if mod.student_amount %>
              <%= "#{mod.student_amount} #{t(:label_elective_block_student_amount_short)}" %>
            <% else %>
              -
            <% end %>
          </td>
          <td>
            <%= link_to t(:label_edit), edit_elective_block_module_path(@elective_block, mod), :class => "edit-element" %>
            <span class="sep">|</span>
            <%= link_to t(:label_destroy), elective_block_module_path(@elective_block, mod), method: :delete, :class => "destroy-element" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center">
          <span>
            <%=t :label_subject_none_added %>
          </span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= f.fields_for :modules, subject_stub do |g| %>
  <%= g.hidden_field :elective_block_id, :value => @elective_block.id %>
  <div class="subsection-header extra-margin">
    <h6>
      <%=t :label_elective_block_new_singular %>
    </h6>
    <hr>
  </div>
  <div class="form-group extra-margin">
    <div class="row">
      <div class="col-md-16">
        <%= g.label :name, t(:label_elective_block_name) %>
        <%= g.text_field :name, :class => "form-control lazy-validate", :placeholder => t(:label_elective_block_name), :rows => 3  %>
      </div>
    </div>
  </div>
  <div class="form-group extra-margin">
    <div class="row">
      <div class="col-md-8">
        <%= g.label :www, t(:label_subject_syllabus_link) %>
        <%= g.text_field :www, :class => "form-control", :placeholder => t(:label_subject_syllabus_link)  %>
      </div>
      <div class="col-md-8">
        <div class="form-group">
          <%= g.label :owner_id, t(:label_module_owner_short) %>
          <%= g.text_field :owner_id, :value => g.object.employee.try(:surname_name), :class => "form-control typeahead-supervisor lazy-validate", :placeholder => t(:label_module_owner_short)  %>
          <%= g.hidden_field :owner_id %>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group extra-margin">
    <div class="row">
      <div class="col-md-4">
        <%= g.label :student_amount, t(:label_elective_block_student_amount) %>
        <%= g.select :student_amount, options_for_select([["--", ""]] | (5..200).step(5).to_a.collect {|i| [i,i] }, g.object.try(:student_amount)), {}, :class => "form-control" %>
      </div>
      <div class="col-md-4">
        <%= g.label :ects_amount, t(:label_ects_amount) %>
        <%= g.select :ects_amount, options_for_select((1..30).collect {|i| [i,i] }, g.object.try(:ects_amount)), {}, :class => "form-control" %>
      </div>
      <div class="col-md-4">
        <%= g.label :semester_number, t(:label_semester) %>
        <%= g.select :semester_number, options_for_select((1..8).collect {|i| [i,i] }, g.object.try(:semester_number)), {}, :class => "form-control" %>
      </div>
    </div>
  </div>
  <hr>
  <div class="pull-right">
    <%= g.button t(:label_cancel), :class => "btn btn-primary cancel-form", :'data-type' => 'subject' %>
    <%= g.submit t(:label_save), :class => "btn btn-danger save-subject" %>
  </div>
  <div class="clearfix"></div>
  <div class="section-footer extra-margin">
    <hr>
  </div>
<% end %>

app/views/graphite/elective_blocks/collection_destroy.json.erb
<%= raw( {:success => @action_performed, :objects => @elective_block_ids }.to_json) %>

app/views/graphite/elective_blocks/destroy.js.erb
$("#elective-block-<%=params[:id]%>").remove();

app/views/graphite/elective_blocks/edit.html.erb
<% content_for :additional_javascript_libraries do %>
  <%= javascript_include_tag "graphite/elective_block" %>
  <%= javascript_include_tag "graphite/edit_elective_block" %>
<% end %>
<% content_for :content_heading do %>
  <div class="row">
    <div class="col-md-9">
      <h4>
        <%=t :label_elective_block_edit%>
      </h4>
    </div>
    <div class="col-md-7">
      <%= render :partial => "elective_block_header"  %>
    </div>
  </div>
<% end %>
<% content_for :content_footnote do %>
  <div class="row">
    <div class="col-md-9">
    </div>
    <div class="col-md-7">
      <%= render :partial => "elective_block_header"  %>
    </div>
  </div>
<% end %>

<%= form_for @elective_block, role: "form", :html => {:class => "elective-block"}  do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>
<div>
  <div class="subject-form">
    <%= form_tag elective_block_modules_path(@elective_block), :method => :post, :class => "save-subject-form" do %>
    <% end %>
  </div>
  <div class="new-subject-form">
    <%= form_tag new_elective_block_module_path(@elective_block), :method => :get, :class => "new-subject-form" do %>
    <% end %>
  </div>
  <div class="block-form">
    <%= form_tag elective_block_blocks_path(@elective_block), :method => :post, :class => "save-block-form" do %>
    <% end %>
  </div>
  <div class="new-block-form">
    <%= form_tag new_elective_block_block_path(@elective_block), :method => :get, :class => "new-block-form" do %>
    <% end %>
  </div>
</div>